version: "3.9"

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bagisto-php
    volumes:
      - ./workspace:/var/www/html
    depends_on:
      mysql:
        condition: service_started
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: bagisto-nginx
    ports:
      - "80:80"
    volumes:
      - ./workspace:/var/www/html
      - ./.configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    restart: unless-stopped

  mysql:
    image: mariadb:10.6
    container_name: bagisto-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bagisto-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: bagisto-mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2G
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
